export default {
  "itemList": [
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331429,
        "title": "新世相x华为乾崑-平凡的日子 揣着满心安",
        "description": "生活不常是坦途，总有些看不见的微澜起伏。一次争吵后的恍惚，一段找不到方向的路，一场突如其来的暴雨……我们曾以为，心安在于避开所有风浪。\n后来才懂，真正的心安，是允许风浪发生，并相信总有一种力量，能接住那些措手不及的瞬间。\n这一次，我们与华为乾崑一起，将镜头对准生活中那些微澜起伏的瞬间，希望这份于细微处的守护，能让每一个你，在平凡的日子里始终揣着心安。",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 0,
          "shareCount": 7,
          "replyCount": 0,
          "realCollectionCount": 0
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "广告",
        "author": {
          "id": 398,
          "icon": "http://ali-img.kaiyanapp.com/f4f2b2205861a02174d3b15eaa00214e.png?imageMogr2/quality/60/format/jpg",
          "name": "新世相",
          "description": "我们终将改变潮水的方向。",
          "link": "",
          "latestReleaseTime": 1765441675000,
          "videoNum": 319,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 398,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 398,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/40482da5b579e16e23b0ddf2b3b3b2f9.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/40482da5b579e16e23b0ddf2b3b3b2f9.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331429&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 186,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331429",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331429&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1765363038000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "新世相x华为乾崑-平凡的日子 揣着满心安",
        "descriptionPgc": "生活不常是坦途，总有些看不见的微澜起伏。一次争吵后的恍惚，一段找不到方向的路，一场突如其来的暴雨……我们曾以为，心安在于避开所有风浪。\n后来才懂，真正的心安，是允许风浪发生，并相信总有一种力量，能接住那些措手不及的瞬间。\n这一次，我们与华为乾崑一起，将镜头对准生活中那些微澜起伏的瞬间，希望这份于细微处的守护，能让每一个你，在平凡的日子里始终揣着心安。",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1765363038000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331428,
        "title": "新世相x华为乾崑《给万千嘱咐的交代》",
        "description": "每句「路上小心」，都是希望你「平安回来」。有一群人，为了这份最日常的牵挂走进实验室，选择与“万一”为敌。他们模拟每一个可能的路口险情，每次下雨、黑暗中的视线模糊，每处不易察觉的道路坑洼。无数次测试，只为避免“万一”的发生。\n这条路无关胜利，只关乎对生命的敬畏。他们相信，所有及时的守护都并非偶然，而是无数次测试与优化后的必然。\n新世相联合华为乾崑共同呈现全新短片，让每次出发，都能安全抵达。",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 0,
          "shareCount": 7,
          "replyCount": 0,
          "realCollectionCount": 0
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "广告",
        "author": {
          "id": 398,
          "icon": "http://ali-img.kaiyanapp.com/f4f2b2205861a02174d3b15eaa00214e.png?imageMogr2/quality/60/format/jpg",
          "name": "新世相",
          "description": "我们终将改变潮水的方向。",
          "link": "",
          "latestReleaseTime": 1765441675000,
          "videoNum": 319,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 398,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 398,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/25fd7a403cc48c23aa7e38f95a35885b.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/25fd7a403cc48c23aa7e38f95a35885b.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331428&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 186,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331428",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331428&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1765363029000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "新世相x华为乾崑《给万千嘱咐的交代》",
        "descriptionPgc": "每句「路上小心」，都是希望你「平安回来」。有一群人，为了这份最日常的牵挂走进实验室，选择与“万一”为敌。他们模拟每一个可能的路口险情，每次下雨、黑暗中的视线模糊，每处不易察觉的道路坑洼。无数次测试，只为避免“万一”的发生。\n这条路无关胜利，只关乎对生命的敬畏。他们相信，所有及时的守护都并非偶然，而是无数次测试与优化后的必然。\n新世相联合华为乾崑共同呈现全新短片，让每次出发，都能安全抵达。",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1765363029000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331427,
        "title": "AI「怪兽公司」，没人比 AI 更懂打工人",
        "description": "这则可爱的 AI 短片用黑色幽默与超现实手法，探讨当代都市「打工人」在职场生态中所承受的心理压力。故事背景设定在架空的 Corpo-Tech 公司，一群职员在日常的机械化工作中逐渐「异化」。随着内部压力的不断累积，原本压抑的氛围最终以一种超乎想象的、极具「破坏性」的方式爆发。作者试图通过视觉与听觉的结合，将抽象的职场焦虑具象化。本短片是一次探索 AI 技术与传统后期制作融合的影像实验。核心视觉素材均由先进的生成式 AI 工具辅助完成。静态概念图： Midjourney；动态视频片段： Luma Labs Dream Machine & Runway Gen-3；声音设计： Eleven Labs (SFX) & Splice (SFX Library)；原创音乐： Udio AI。From Pizza Later",
        "library": "DAILY",
        "tags": [
          {
            "id": 744,
            "name": "每日创意灵感",
            "actionUrl": "eyepetizer://tag/744/?title=%E6%AF%8F%E6%97%A5%E5%88%9B%E6%84%8F%E7%81%B5%E6%84%9F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 144,
            "name": "魔性",
            "actionUrl": "eyepetizer://tag/144/?title=%E9%AD%94%E6%80%A7",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/f7a6f01d5425dcba563ef114501c169e.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/f7a6f01d5425dcba563ef114501c169e.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 140,
            "name": "搞笑",
            "actionUrl": "eyepetizer://tag/140/?title=%E6%90%9E%E7%AC%91",
            "adTrack": null,
            "desc": "哈哈哈哈哈哈哈哈",
            "bgPicture": "http://img.kaiyanapp.com/f787d5053443499e8d787911cd8b3876.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/f2b803d3c383bba5a3888b2709160b6e.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 797,
            "name": "人工智能",
            "actionUrl": "eyepetizer://tag/797/?title=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 174,
            "name": "治愈",
            "actionUrl": "eyepetizer://tag/174/?title=%E6%B2%BB%E6%84%88",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/5417e0d8f72d7bb3f1cd69eb75b0759e.jpeg?imageMogr2/quality/60",
            "headerImage": "http://img.kaiyanapp.com/5417e0d8f72d7bb3f1cd69eb75b0759e.jpeg?imageMogr2/quality/60",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 170,
            "name": "幽默",
            "actionUrl": "eyepetizer://tag/170/?title=%E5%B9%BD%E9%BB%98",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/8164ded95cfde8c5f42acf243c6ca3e6.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/8164ded95cfde8c5f42acf243c6ca3e6.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 168,
            "name": "讽刺",
            "actionUrl": "eyepetizer://tag/168/?title=%E8%AE%BD%E5%88%BA",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/a3de18fb448aa41a140f1901130c380a.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/d536b9c09b2681630afcc92222599f0e.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 1023,
            "name": "动画",
            "actionUrl": "eyepetizer://tag/1023/?title=%E5%8A%A8%E7%94%BB",
            "adTrack": null,
            "desc": "有趣的人永远不缺童心",
            "bgPicture": "http://img.kaiyanapp.com/349cbd33cdf71fc74d5e9c7a00b444fd.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/208aa67386c045497389f015ae28dd29.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 2,
            "name": "创意",
            "actionUrl": "eyepetizer://tag/2/?title=%E5%88%9B%E6%84%8F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/1b457058cf2b317304ff9f70543c040d.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/fdefdb34cbe3d2ac9964d306febe9025.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          }
        ],
        "consumption": {
          "collectionCount": 227,
          "shareCount": 34,
          "replyCount": 3,
          "realCollectionCount": 120
        },
        "resourceType": "video",
        "slogan": "",
        "provider": {
          "name": "YouTube",
          "alias": "youtube",
          "icon": "http://ali-img.kaiyanapp.com/fa20228bc5b921e837156923a58713f6.png"
        },
        "category": "创意",
        "author": {
          "id": 2161,
          "icon": "http://ali-img.kaiyanapp.com/f4a9aba1c6857ee0cefcdc5aee0a1fc9.png?imageMogr2/quality/60/format/jpg",
          "name": "全球创意视频精选",
          "description": "我们精选最有创意的视频，我们用技术与审美结合，探索视觉的无限可能。",
          "link": "",
          "latestReleaseTime": 1764075594000,
          "videoNum": 2408,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 2161,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2161,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/7a3435a1b57c5c78664d55ea12372a2b.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/7a3435a1b57c5c78664d55ea12372a2b.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/22999f0521b1ca872eb4f82e4b6711cf.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": "http://img.kaiyanapp.com/7a3435a1b57c5c78664d55ea12372a2b.png?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331427&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": "",
        "duration": 58,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331427",
          "forWeibo": "http://www.eyepetizer.net/detail.html?vid=331427"
        },
        "releaseTime": 1764075594000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "",
        "descriptionPgc": "",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1764075594000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "这则可爱的 AI 短片用黑色幽默与超现实手法，探讨当代都市「打工人」在职场生态中所承受的心理压力。故事背景设定在架空的 Corpo-Tech 公司，一群职员在日常的机械化工作中逐渐「异化」。随着内部压力的不断累积，原本压抑的氛围最终以一种超乎想象的、极具「破坏性」的方式爆发。作者试图通过视觉与听觉的结合，将抽象的职场焦虑具象化。本短片是一次探索 AI 技术与传统后期制作融合的影像实验。核心视觉素材均由先进的生成式 AI 工具辅助完成。静态概念图： Midjourney；动态视频片段： Luma Labs Dream Machine & Runway Gen-3；声音设计： Eleven Labs (SFX) & Splice (SFX Library)；原创音乐： Udio AI。From Pizza Later",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331419,
        "title": "亚洲女性作家系列访谈｜ 郑世朗篇",
        "description": "“每当气喘吁吁的时候，我常会想，再走一步吧，再试一次吧。” \n新世相推出亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第五期，我们对谈韩国作家-郑世朗\n \n在郑世朗笔下，生活里的困顿被揉进奇幻想象，构筑成一个天马行空的文字宇宙。文学创作就是看见裂缝，而这些裂缝终会相遇。\n \n本系列由女性品牌 大人糖 特别支持，\n邀你一同看见：渴望本身，就是一点点拉近未来的力量。",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 6,
          "shareCount": 0,
          "replyCount": 0,
          "realCollectionCount": 6
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "记录",
        "author": {
          "id": 398,
          "icon": "http://ali-img.kaiyanapp.com/f4f2b2205861a02174d3b15eaa00214e.png?imageMogr2/quality/60/format/jpg",
          "name": "新世相",
          "description": "我们终将改变潮水的方向。",
          "link": "",
          "latestReleaseTime": 1765441675000,
          "videoNum": 319,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 398,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 398,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/f3632f7562682f1d9274940d78bac061.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/f3632f7562682f1d9274940d78bac061.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331419&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 561,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331419",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331419&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1763887083000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "亚洲女性作家系列访谈｜ 郑世朗篇",
        "descriptionPgc": "“每当气喘吁吁的时候，我常会想，再走一步吧，再试一次吧。” \n新世相推出亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第五期，我们对谈韩国作家-郑世朗\n \n在郑世朗笔下，生活里的困顿被揉进奇幻想象，构筑成一个天马行空的文字宇宙。文学创作就是看见裂缝，而这些裂缝终会相遇。\n \n本系列由女性品牌 大人糖 特别支持，\n邀你一同看见：渴望本身，就是一点点拉近未来的力量。",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1763887083000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331413,
        "title": "AI 武侠巨制「一代少林宗师」",
        "description": "这神秘的外来者与僧人——此非杀伐，而是另一种修行。这是作者 Dave Clark 酝酿许久的功夫史诗，他使用了多种AI工具，辅助他完成这部作品。使用到的工具和制作流程：故事板：Adobe Firefly Boards剧本创作：本人与 Google Gemini；初始图像：Midjourney；图像迭代：Freepik、Seedream、Nano Banana；视频生成：Luma Labs Ray3、Google Veo 3、Flow by Google；图像润饰：Photoshop、Freepik；图像超清化：Magnific AI；音效：Eleven Labs；剪辑：Premiere Pro；调色：Davinci Resolve（结合 FilmConvert）；音乐：Suno Music（灵感源自《功夫》）。From AI Director Dave Clark",
        "library": "DAILY",
        "tags": [
          {
            "id": 744,
            "name": "每日创意灵感",
            "actionUrl": "eyepetizer://tag/744/?title=%E6%AF%8F%E6%97%A5%E5%88%9B%E6%84%8F%E7%81%B5%E6%84%9F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 200,
            "name": "酷炫",
            "actionUrl": "eyepetizer://tag/200/?title=%E9%85%B7%E7%82%AB",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/71f39f985df512d0d9fb52b82737bcf5.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/71f39f985df512d0d9fb52b82737bcf5.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 166,
            "name": "悲剧",
            "actionUrl": "eyepetizer://tag/166/?title=%E6%82%B2%E5%89%A7",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/ceb623331c9d83139362595b6faa7d04.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/ceb623331c9d83139362595b6faa7d04.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 184,
            "name": "动作",
            "actionUrl": "eyepetizer://tag/184/?title=%E5%8A%A8%E4%BD%9C",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/fa94d59f50029fa8e89f66d5e9c1fba2.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/b947a25b04e8f5f38bc6aa9672e44489.jpeg?imageMogr2/quality/60",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 130,
            "name": "悬疑",
            "actionUrl": "eyepetizer://tag/130/?title=%E6%82%AC%E7%96%91",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/d486babd4c69bfd4de45462d1341b64b.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/d486babd4c69bfd4de45462d1341b64b.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 122,
            "name": "科幻",
            "actionUrl": "eyepetizer://tag/122/?title=%E7%A7%91%E5%B9%BB",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/417a8466c670ccde688bb4b525ddf23d.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/114beec25470880881352171834ddf43.jpeg?imageMogr2/quality/60",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 124,
            "name": "魔幻",
            "actionUrl": "eyepetizer://tag/124/?title=%E9%AD%94%E5%B9%BB",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/8dd88a4526355610ccfb537c08e15458.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/8dd88a4526355610ccfb537c08e15458.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 2,
            "name": "创意",
            "actionUrl": "eyepetizer://tag/2/?title=%E5%88%9B%E6%84%8F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/1b457058cf2b317304ff9f70543c040d.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/fdefdb34cbe3d2ac9964d306febe9025.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 12,
            "name": "剧情",
            "actionUrl": "eyepetizer://tag/12/?title=%E5%89%A7%E6%83%85",
            "adTrack": null,
            "desc": "用一个好故事，描绘生活的不可思议",
            "bgPicture": "http://img.kaiyanapp.com/945fa937f0955b31224314a4eeef59b8.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/945fa937f0955b31224314a4eeef59b8.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 797,
            "name": "人工智能",
            "actionUrl": "eyepetizer://tag/797/?title=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          }
        ],
        "consumption": {
          "collectionCount": 173,
          "shareCount": 66,
          "replyCount": 7,
          "realCollectionCount": 106
        },
        "resourceType": "video",
        "slogan": "",
        "provider": {
          "name": "YouTube",
          "alias": "youtube",
          "icon": "http://ali-img.kaiyanapp.com/fa20228bc5b921e837156923a58713f6.png"
        },
        "category": "创意",
        "author": {
          "id": 2161,
          "icon": "http://ali-img.kaiyanapp.com/f4a9aba1c6857ee0cefcdc5aee0a1fc9.png?imageMogr2/quality/60/format/jpg",
          "name": "全球创意视频精选",
          "description": "我们精选最有创意的视频，我们用技术与审美结合，探索视觉的无限可能。",
          "link": "",
          "latestReleaseTime": 1764075594000,
          "videoNum": 2408,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 2161,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2161,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/54adbc35f2042f27989cf17ec116c37a.jpeg?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/54adbc35f2042f27989cf17ec116c37a.jpeg?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/11d6e3bd4017c56ebde225975fd55608.jpeg?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": "http://img.kaiyanapp.com/54adbc35f2042f27989cf17ec116c37a.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331413&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": "",
        "duration": 81,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331413",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331413&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1763773234000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "",
        "descriptionPgc": "",
        "remark": "  ",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1763773234000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "这神秘的外来者与僧人——此非杀伐，而是另一种修行。这是作者 Dave Clark 酝酿许久的功夫史诗，他使用了多种AI工具，辅助他完成这部作品。使用到的工具和制作流程：故事板：Adobe Firefly Boards剧本创作：本人与 Google Gemini；初始图像：Midjourney；图像迭代：Freepik、Seedream、Nano Banana；视频生成：Luma Labs Ray3、Google Veo 3、Flow by Google；图像润饰：Photoshop、Freepik；图像超清化：Magnific AI；音效：Eleven Labs；剪辑：Premiere Pro；调色：Davinci Resolve（结合 FilmConvert）；音乐：Suno Music（灵感源自《功夫》）。From AI Director Dave Clark",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331414,
        "title": "亚洲女性作家系列访谈｜ 贺淑芳篇",
        "description": "女性内心深处的感受好似月亮的背面，混沌而隐秘。\n亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第四期对谈：华裔马来西亚作家-贺淑芳。\n \n“我们是透过欲望才能成长的。” 从童年阅读男性作家作品时隐隐感到的距离，到相信艺术就是经验的创作者，贺淑芳让文字成为折射内在的棱镜，映照出属于女性们的集体故事。\n \n本系列由女性品牌 大人糖 特别支持\n邀你一同看见：她们执笔，让被屏蔽的故事发出声响。",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 12,
          "shareCount": 0,
          "replyCount": 0,
          "realCollectionCount": 6
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "记录",
        "author": {
          "id": 398,
          "icon": "http://ali-img.kaiyanapp.com/f4f2b2205861a02174d3b15eaa00214e.png?imageMogr2/quality/60/format/jpg",
          "name": "新世相",
          "description": "我们终将改变潮水的方向。",
          "link": "",
          "latestReleaseTime": 1765441675000,
          "videoNum": 319,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 398,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 398,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/ac01ff97be526ecab716c7da7fa8e06f.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/ac01ff97be526ecab716c7da7fa8e06f.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331414&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 782,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331414",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331414&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1763456057000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "亚洲女性作家系列访谈｜ 贺淑芳篇",
        "descriptionPgc": "女性内心深处的感受好似月亮的背面，混沌而隐秘。\n亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第四期对谈：华裔马来西亚作家-贺淑芳。\n \n“我们是透过欲望才能成长的。” 从童年阅读男性作家作品时隐隐感到的距离，到相信艺术就是经验的创作者，贺淑芳让文字成为折射内在的棱镜，映照出属于女性们的集体故事。\n \n本系列由女性品牌 大人糖 特别支持\n邀你一同看见：她们执笔，让被屏蔽的故事发出声响。",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1763456057000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331406,
        "title": "末世感神秘主义，AI 的隐喻「饕餮」",
        "description": "这支 AI 创作短片荣获 2025 年 Runway 平台 Gen:48 第四季限时创作大赛「大众选择奖」。「盛宴」是一部关于牺牲、亵渎与痛苦抗争的无声诗剧。影片以漆黑无垠的荒漠为舞台，演绎永无止境的奉献如何崩裂成复仇火焰。在凝固的静谧之下，潜伏着女性怒火的暗涌——这场关于价值、存在与尊严的冥思，全程在 48 小时内创作完成。作为 Gen:48 第四季 AI 电影竞赛作品，所有团队在周六清晨才获知创作主题，并于周一清晨前完成最终提交。From Alex Naghavi",
        "library": "DAILY",
        "tags": [
          {
            "id": 744,
            "name": "每日创意灵感",
            "actionUrl": "eyepetizer://tag/744/?title=%E6%AF%8F%E6%97%A5%E5%88%9B%E6%84%8F%E7%81%B5%E6%84%9F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 797,
            "name": "人工智能",
            "actionUrl": "eyepetizer://tag/797/?title=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 783,
            "name": "惊悚电影",
            "actionUrl": "eyepetizer://tag/783/?title=%E6%83%8A%E6%82%9A%E7%94%B5%E5%BD%B1",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/b6265dd79b31eab8393e6315b5f27080.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/b6265dd79b31eab8393e6315b5f27080.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 2,
            "name": "创意",
            "actionUrl": "eyepetizer://tag/2/?title=%E5%88%9B%E6%84%8F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/1b457058cf2b317304ff9f70543c040d.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/fdefdb34cbe3d2ac9964d306febe9025.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          }
        ],
        "consumption": {
          "collectionCount": 225,
          "shareCount": 100,
          "replyCount": 4,
          "realCollectionCount": 199
        },
        "resourceType": "video",
        "slogan": "",
        "provider": {
          "name": "YouTube",
          "alias": "youtube",
          "icon": "http://ali-img.kaiyanapp.com/fa20228bc5b921e837156923a58713f6.png"
        },
        "category": "创意",
        "author": {
          "id": 2161,
          "icon": "http://ali-img.kaiyanapp.com/f4a9aba1c6857ee0cefcdc5aee0a1fc9.png?imageMogr2/quality/60/format/jpg",
          "name": "全球创意视频精选",
          "description": "我们精选最有创意的视频，我们用技术与审美结合，探索视觉的无限可能。",
          "link": "",
          "latestReleaseTime": 1764075594000,
          "videoNum": 2408,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 2161,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2161,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/d7c62321be44f0966845ca9a7a2d174d.jpeg?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/d7c62321be44f0966845ca9a7a2d174d.jpeg?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/03a1c7cad19faac4ae2a7ce4b7f2fc4d.jpeg?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": "http://img.kaiyanapp.com/d7c62321be44f0966845ca9a7a2d174d.jpeg?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331406&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": "",
        "duration": 122,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331406",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331406&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1762909252000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "",
        "descriptionPgc": "",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1762909252000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "这支 AI 创作短片荣获 2025 年 Runway 平台 Gen:48 第四季限时创作大赛「大众选择奖」。「盛宴」是一部关于牺牲、亵渎与痛苦抗争的无声诗剧。影片以漆黑无垠的荒漠为舞台，演绎永无止境的奉献如何崩裂成复仇火焰。在凝固的静谧之下，潜伏着女性怒火的暗涌——这场关于价值、存在与尊严的冥思，全程在 48 小时内创作完成。作为 Gen:48 第四季 AI 电影竞赛作品，所有团队在周六清晨才获知创作主题，并于周一清晨前完成最终提交。From Alex Naghavi",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331395,
        "title": "秋日限定，板栗烧鸡巨香巨好吃～保姆教程！",
        "description": "秋风起，栗子香#粉糯香醇无水板栗烧鸡# 是时令馈赠的经典家常菜，也是秋冬季滋养脾胃的好吃养生菜！这次分享我的靠谱配方，且借助压力锅，烹饪只需10分钟。开锅瞬间，香气扑鼻——鸡肉已臻脱骨之境，板栗也吸饱了丰腴的肉汁。两种食材的天然香气释放得恰到好处，米饭绝杀！\n在秋收冬藏的时节里，我们就用最简单的方式，随时随地为自己和家人温暖进补，开心吃饭吧！",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 6,
          "shareCount": 0,
          "replyCount": 0,
          "realCollectionCount": 0
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "开胃",
        "author": {
          "id": 2951,
          "icon": "http://ali-img.kaiyanapp.com/d0d7ecc41dfa76c1481c4b064007d01c.png?imageMogr2/quality/60/format/jpg",
          "name": "任芸丽",
          "description": "任芸丽：美食作家，资深媒体人。\n《食盐Salt》总编，《贝太厨房》前全媒体主编，《乐生活空间》、《素味乐生活》新媒体主编，《吃情十物》、《甜蜜食堂》作者，乐生活公益课堂项目发起人。",
          "link": "",
          "latestReleaseTime": 1763887133000,
          "videoNum": 407,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 2951,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2951,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/96496a9d2e0a55b19583797c334a7269.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/96496a9d2e0a55b19583797c334a7269.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331395&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 270,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331395",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331395&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1762844808000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "秋日限定，板栗烧鸡巨香巨好吃～保姆教程！",
        "descriptionPgc": "秋风起，栗子香#粉糯香醇无水板栗烧鸡# 是时令馈赠的经典家常菜，也是秋冬季滋养脾胃的好吃养生菜！这次分享我的靠谱配方，且借助压力锅，烹饪只需10分钟。开锅瞬间，香气扑鼻——鸡肉已臻脱骨之境，板栗也吸饱了丰腴的肉汁。两种食材的天然香气释放得恰到好处，米饭绝杀！\n在秋收冬藏的时节里，我们就用最简单的方式，随时随地为自己和家人温暖进补，开心吃饭吧！",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1762844808000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331394,
        "title": "亚洲女性作家系列访谈｜ 伊藤比吕美篇",
        "description": "如果有人在荒地里率先挥下锄头，之后会有越来越多的人来耕这片田，播下种子。 \n新世相推出亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第三期，我们对谈日本作家-伊藤比吕美\n \n她不追求正确，也不代表谁；她只是表达女性的真实经验。今天，70岁的她用自己的经历告诉我们：衰老不是生命的坍塌，它是另一种生长。\n \n本系列由女性品牌大人糖特别支持，\n邀你一同看见：你属于你自己，请时刻思考自己想怎样生活",
        "library": "DEFAULT",
        "tags": [],
        "consumption": {
          "collectionCount": 13,
          "shareCount": 22,
          "replyCount": 0,
          "realCollectionCount": 0
        },
        "resourceType": "video",
        "slogan": null,
        "provider": {
          "name": "PGC",
          "alias": "PGC",
          "icon": ""
        },
        "category": "记录",
        "author": {
          "id": 398,
          "icon": "http://ali-img.kaiyanapp.com/f4f2b2205861a02174d3b15eaa00214e.png?imageMogr2/quality/60/format/jpg",
          "name": "新世相",
          "description": "我们终将改变潮水的方向。",
          "link": "",
          "latestReleaseTime": 1765441675000,
          "videoNum": 319,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 398,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 398,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/6673a006aa8bf9f189b8a3892c228e89.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/6673a006aa8bf9f189b8a3892c228e89.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/6e9f4b114dc1c454e2fb0e86ebbace52.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": null
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331394&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": null,
        "duration": 1093,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331394",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331394&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1762844759000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "亚洲女性作家系列访谈｜ 伊藤比吕美篇",
        "descriptionPgc": "如果有人在荒地里率先挥下锄头，之后会有越来越多的人来耕这片田，播下种子。 \n新世相推出亚洲女性作家访谈系列——《她声不止：每个“她”的故事，都藏着“她们”》。\n第三期，我们对谈日本作家-伊藤比吕美\n \n她不追求正确，也不代表谁；她只是表达女性的真实经验。今天，70岁的她用自己的经历告诉我们：衰老不是生命的坍塌，它是另一种生长。\n \n本系列由女性品牌大人糖特别支持，\n邀你一同看见：你属于你自己，请时刻思考自己想怎样生活",
        "remark": "",
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1762844759000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    },
    {
      "type": "video",
      "data": {
        "dataType": "VideoBeanForClient",
        "id": 331393,
        "title": "纽约地铁被火烈鸟占领！？？",
        "description": "这是由 Runway 官方发布的 Gen 4 视频生成模型的广告片。当纽约变成「疯狂动物城」，被各种猛兽占领后，是不是也隐喻着人类世界也将会被 AI「占领」？From Runway",
        "library": "DAILY",
        "tags": [
          {
            "id": 744,
            "name": "每日创意灵感",
            "actionUrl": "eyepetizer://tag/744/?title=%E6%AF%8F%E6%97%A5%E5%88%9B%E6%84%8F%E7%81%B5%E6%84%9F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/bc2479c09cd15cb93b69d82e5f21c3fc.png?imageMogr2/quality/60/format/jpg",
            "tagRecType": "IMPORTANT",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 174,
            "name": "治愈",
            "actionUrl": "eyepetizer://tag/174/?title=%E6%B2%BB%E6%84%88",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/5417e0d8f72d7bb3f1cd69eb75b0759e.jpeg?imageMogr2/quality/60",
            "headerImage": "http://img.kaiyanapp.com/5417e0d8f72d7bb3f1cd69eb75b0759e.jpeg?imageMogr2/quality/60",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 172,
            "name": "什么鬼",
            "actionUrl": "eyepetizer://tag/172/?title=%E4%BB%80%E4%B9%88%E9%AC%BC",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/e6b5568e865b26f3f84270e613955e59.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/e6b5568e865b26f3f84270e613955e59.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 162,
            "name": "无厘头",
            "actionUrl": "eyepetizer://tag/162/?title=%E6%97%A0%E5%8E%98%E5%A4%B4",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/3a5752f4b99d70debee8d099ef6a49a7.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/3a5752f4b99d70debee8d099ef6a49a7.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 104,
            "name": "鬼畜",
            "actionUrl": "eyepetizer://tag/104/?title=%E9%AC%BC%E7%95%9C",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/3f137282d738483b32cf4cd9da2c2c43.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/3f137282d738483b32cf4cd9da2c2c43.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 124,
            "name": "魔幻",
            "actionUrl": "eyepetizer://tag/124/?title=%E9%AD%94%E5%B9%BB",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/8dd88a4526355610ccfb537c08e15458.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/8dd88a4526355610ccfb537c08e15458.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 346,
            "name": "美国",
            "actionUrl": "eyepetizer://tag/346/?title=%E7%BE%8E%E5%9B%BD",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/19b625e7277199ed752fe61a56a596f2.jpeg?imageMogr2/quality/100",
            "headerImage": "http://img.kaiyanapp.com/19b625e7277199ed752fe61a56a596f2.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 2,
            "name": "创意",
            "actionUrl": "eyepetizer://tag/2/?title=%E5%88%9B%E6%84%8F",
            "adTrack": null,
            "desc": "技术与审美结合，探索视觉的无限可能",
            "bgPicture": "http://img.kaiyanapp.com/1b457058cf2b317304ff9f70543c040d.png?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/fdefdb34cbe3d2ac9964d306febe9025.jpeg?imageMogr2/quality/100",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 16,
            "name": "广告",
            "actionUrl": "eyepetizer://tag/16/?title=%E5%B9%BF%E5%91%8A",
            "adTrack": null,
            "desc": "为广告人的精彩创意点赞",
            "bgPicture": "http://img.kaiyanapp.com/e41e74fe73882b552de00d95d56748d2.jpeg?imageMogr2/quality/60",
            "headerImage": "http://img.kaiyanapp.com/23d1a1dce9756535d314aed3cf9777a0.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          },
          {
            "id": 797,
            "name": "人工智能",
            "actionUrl": "eyepetizer://tag/797/?title=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD",
            "adTrack": null,
            "desc": null,
            "bgPicture": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "headerImage": "http://img.kaiyanapp.com/6a8eb7804afb358f81bc0700a9107d36.jpeg?imageMogr2/quality/60/format/jpg",
            "tagRecType": "NORMAL",
            "childTagList": null,
            "childTagIdList": null,
            "haveReward": false,
            "ifNewest": false,
            "newestEndTime": null,
            "communityIndex": 0
          }
        ],
        "consumption": {
          "collectionCount": 282,
          "shareCount": 77,
          "replyCount": 6,
          "realCollectionCount": 173
        },
        "resourceType": "video",
        "slogan": "",
        "provider": {
          "name": "YouTube",
          "alias": "youtube",
          "icon": "http://ali-img.kaiyanapp.com/fa20228bc5b921e837156923a58713f6.png"
        },
        "category": "创意",
        "author": {
          "id": 2161,
          "icon": "http://ali-img.kaiyanapp.com/f4a9aba1c6857ee0cefcdc5aee0a1fc9.png?imageMogr2/quality/60/format/jpg",
          "name": "全球创意视频精选",
          "description": "我们精选最有创意的视频，我们用技术与审美结合，探索视觉的无限可能。",
          "link": "",
          "latestReleaseTime": 1764075594000,
          "videoNum": 2408,
          "adTrack": null,
          "follow": {
            "itemType": "author",
            "itemId": 2161,
            "followed": false
          },
          "shield": {
            "itemType": "author",
            "itemId": 2161,
            "shielded": false
          },
          "approvedNotReadyVideoCount": 0,
          "ifPgc": true,
          "recSort": 0,
          "expert": false
        },
        "cover": {
          "feed": "http://ali-img.kaiyanapp.com/7bbc5546d4f2a4880bf14d3307edee13.png?imageMogr2/quality/60/format/jpg",
          "detail": "http://ali-img.kaiyanapp.com/7bbc5546d4f2a4880bf14d3307edee13.png?imageMogr2/quality/60/format/jpg",
          "blurred": "http://ali-img.kaiyanapp.com/a9a22c6e9b3dad70ff414d1b52fe732f.png?imageMogr2/quality/60/format/jpg",
          "sharing": null,
          "homepage": "http://img.kaiyanapp.com/7bbc5546d4f2a4880bf14d3307edee13.png?imageView2/1/w/720/h/560/format/jpg/q/75|watermark/1/image/aHR0cDovL2ltZy5rYWl5YW5hcHAuY29tL2JsYWNrXzMwLnBuZw==/dissolve/100/gravity/Center/dx/0/dy/0|imageslim"
        },
        "playUrl": "http://baobab.kaiyanapp.com/api/v1/playUrl?vid=331393&resourceType=video&editionType=default&source=aliyun&playUrlType=url_oss&udid=",
        "thumbPlayUrl": "",
        "duration": 67,
        "webUrl": {
          "raw": "http://www.eyepetizer.net/detail.html?vid=331393",
          "forWeibo": "https://m.eyepetizer.net/u1/video-detail?video_id=331393&resource_type=video&utm_campaign=routine&utm_medium=share&utm_source=weibo&uid=0"
        },
        "releaseTime": 1762304418000,
        "playInfo": [],
        "campaign": null,
        "waterMarks": null,
        "ad": false,
        "adTrack": [],
        "type": "NORMAL",
        "titlePgc": "",
        "descriptionPgc": "",
        "remark": null,
        "ifLimitVideo": false,
        "searchWeight": 0,
        "brandWebsiteInfo": null,
        "videoPosterBean": null,
        "idx": 0,
        "shareAdTrack": null,
        "favoriteAdTrack": null,
        "webAdTrack": null,
        "date": 1762304418000,
        "promotion": null,
        "label": null,
        "labelList": [],
        "descriptionEditor": "这是由 Runway 官方发布的 Gen 4 视频生成模型的广告片。当纽约变成「疯狂动物城」，被各种猛兽占领后，是不是也隐喻着人类世界也将会被 AI「占领」？From Runway",
        "collected": false,
        "reallyCollected": false,
        "played": false,
        "subtitles": [],
        "lastViewTime": null,
        "playlists": null,
        "src": null,
        "recallSource": null,
        "recall_source": null
      },
      "trackingData": null,
      "tag": null,
      "id": 0,
      "adIndex": -1
    }
  ],
  "count": 10,
  "total": 0,
  "nextPageUrl": "http://baobab.kaiyanapp.com/api/v4/discovery/hot?start=11&num=10",
  "adExist": false
}
